"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const createConcessionController_js_1 = require("../controllers/createConcessionController.js");
const deleteConcessionController_js_1 = require("../controllers/deleteConcessionController.js");
const getConcessionsController_js_1 = require("../controllers/getConcessionsController.js");
const updateConcessionsController_js_1 = require("../controllers/updateConcessionsController.js");
const getAllConcessionsController_js_1 = require("../controllers/getAllConcessionsController.js");
const router = (0, express_1.Router)();
exports.router = router;
router.post('/api/v1/concession', createConcessionController_js_1.createConcession);
router.put('/api/v1/concession', updateConcessionsController_js_1.updateConcession);
router.get('/api/v1/concessions', getConcessionsController_js_1.getConcessions);
router.get('/api/v1/concessions/all', getAllConcessionsController_js_1.getAllConcessions);
router.delete('/api/v1/concession', deleteConcessionController_js_1.deleteConcession);
