"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const createConfirmationController_js_1 = require("../controllers/createConfirmationController.js");
const deleteConfirmationController_js_1 = require("../controllers/deleteConfirmationController.js");
const getConfirmationsController_js_1 = require("../controllers/getConfirmationsController.js");
const router = (0, express_1.Router)();
exports.router = router;
router.post('/api/v1/confirmation', createConfirmationController_js_1.createConfirmation);
router.get('/api/v1/confirmation', getConfirmationsController_js_1.getConfirmations);
router.delete('/api/v1/confirmation', deleteConfirmationController_js_1.deleteConfirmation);
