version: '3.7'
services:
  movies_app:
    ports:
      - "4004:4004"
    depends_on:
      mysql_movies:
        condition: service_healthy
    build: ./microservices/movies
    links:
      - "mysql_movies"
    environment:
      MYSQL_URL: mysql_movies
      MYSQL_PORT: 5004
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: db

  mysql_movies:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: password # Password for root access
      MYSQL_TCP_PORT: 5004
    ports:
      - '5004:5004' # <Port exposed> : < MySQL Port running inside container>
    expose:
      - '5004' # Opens port 5004 on the container
    volumes: # Where our data will be persisted
      - mysql_movies_data:/data/db
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 4

volumes:
  mysql_movies_data: