version: '3.9'
services:
  theaters:
    build: ./microservices/theaters
    ports:
      - "4009:4009"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
      
  concessions:
    build: ./microservices/concessions
    ports:
      - "4001:4001"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin

  confirmations:
    build: ./microservices/confirmations
    ports:
      - "4002:4002"
    depends_on:
      - mongodb_container
    environment:
      DATABASE_URL: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
      EMAIL: ts5588881@gmail.com
      PASS: eluthowaiqrpsazk

  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongodb_data_container:/data/db
    command: --quiet
volumes:
  mongodb_data_container: