"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const createTheaterController_js_1 = require("../controllers/createTheaterController.js");
const deleteTheaterController_js_1 = require("../controllers/deleteTheaterController.js");
const getTheatersController_js_1 = require("../controllers/getTheatersController.js");
const updateTheatersController_js_1 = require("../controllers/updateTheatersController.js");
const getAllTheatersController_js_1 = require("../controllers/getAllTheatersController.js");
const router = (0, express_1.Router)();
exports.router = router;
router.post('/api/v1/theater', createTheaterController_js_1.createTheater);
router.put('/api/v1/theater', updateTheatersController_js_1.updateTheater);
router.get('/api/v1/theaters', getTheatersController_js_1.getTheaters);
router.get('/api/v1/theaters/all', getAllTheatersController_js_1.getAllTheaters);
router.delete('/api/v1/theater', deleteTheaterController_js_1.deleteTheaters);
