"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const createMovieController_js_1 = require("../controllers/createMovieController.js");
const deleteMovieController_js_1 = require("../controllers/deleteMovieController.js");
const getMoviesController_js_1 = require("../controllers/getMoviesController.js");
const updateMoviesController_js_1 = require("../controllers/updateMoviesController.js");
const getAllMoviesController_js_1 = require("../controllers/getAllMoviesController.js");
const router = (0, express_1.Router)();
exports.router = router;
router.post('/api/v1/movie', createMovieController_js_1.createMovie);
router.put('/api/v1/movie', updateMoviesController_js_1.updateMovie);
router.get('/api/v1/movies', getMoviesController_js_1.getMovies);
router.get('/api/v1/movies/all', getAllMoviesController_js_1.getAllMovies);
router.delete('/api/v1/movie', deleteMovieController_js_1.deleteMovie);
