apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: movie-ops
  name: movie-ops
spec:
  ports:
    - name: "4003"
      port: 4003
      targetPort: 4003
  selector:
    io.kompose.service: movie-ops
status:
  loadBalancer: {}
