apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: movie-ops
  name: movie-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movie-ops
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: movie-ops
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
          image: movie-ops
          name: movie-ops
          ports:
            - containerPort: 4003
          resources: {}
      restartPolicy: Always
status: {}
