apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: movies
  name: movies
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: movies
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: movies
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: db
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_PORT
              value: "5004"
            - name: MYSQL_URL
              value: mysql_movies
            - name: MYSQL_USER
              value: root
          image: movies
          name: movies
          ports:
            - containerPort: 4004
          resources: {}
      restartPolicy: Always
status: {}
