apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: theaters
  name: theaters
spec:
  ports:
    - name: "4009"
      port: 4009
      targetPort: 4009
  selector:
    io.kompose.service: theaters
status:
  loadBalancer: {}
