apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: theaters
  name: theaters
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: theaters
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: theaters
    spec:
      containers:
        - env:
            - name: DATABASE_URL
              value: mongodb://root:rootpassword@mongodb_container:27017/mydb?directConnection=true&authSource=admin
          image: theaters
          name: theaters
          ports:
            - containerPort: 4009
          resources: {}
      restartPolicy: Always
status: {}
